version: '3'

services:
  brother_scanner:
    container_name: brother_scanner
    image: ghcr.io/alois-gaucher/brother-scanner
    network_mode: host
    restart: unless-stopped
    environment:
      - NAME=SCANNER
      - MODEL=DLP-L2530DW
      - IPADDRESS=192.168.1.58
      - RESOLUTION=600
    volumes:
      - ./scans:/scans
      - ./script:/opt/brother/scanner/brscan-skey/script/

