version: '3'

volumes:
  brotherscanner_script:

services:
  brother-scanner:
    container_name: brother-scanner
    image: ghcr.io/alois-gaucher/brother-scanner
    network_mode: host
    restart: unless-stopped
    environment:
      - NAME=SCANNER
      - MODEL=DLP-L2530DW
      - IPADDRESS=192.168.1.58
      - RESOLUTION=600
    volumes:
      - ./scans:/scans
      - brotherscanner_script:/opt/brother/scanner/brscan-skey/script/

